apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: micro-demo
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ["sh", "-c"]
        args:
          - >
            echo "Waiting for DB...";
            while ! nc -z db 3306; do
              echo "DB not ready, sleeping 3s...";
              sleep 3;
            done;
            echo "DB ready!"

      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.backend.env.DB_PASSWORD | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: micro-demo
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
