apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.backend.env.DB_PASSWORD | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
