# GitHub Actions CI pipeline for microservices-demo-local
# This workflow builds and tests backend and frontend Docker images on every push

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: demo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: backend:test
          load: true

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: frontend:test
          load: true

      - name: Test backend container
        run: |
          docker run --rm --network host -e PORT=5000 -e DB_HOST=localhost -e DB_USER=root -e DB_PASSWORD=example -e DB_NAME=demo backend:test &
          sleep 10
          curl -f http://localhost:5000/api/users

      - name: Test frontend container
        run: |
          docker run --rm --network host -e PORT=3000 -e BACKEND_URL=http://localhost:5000 frontend:test &
          sleep 10
          curl -f http://localhost:3000/

# This workflow ensures Docker images build and basic endpoints respond
# You can extend it to push images or deploy to Kubernetes
