# GitHub Actions CI pipeline for microservices-demo-local
# This workflow builds and tests backend and frontend Docker images on every push

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: demo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" --health-interval=3s --health-timeout=3s --health-retries=2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: backend:test
          load: true

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: frontend:test
          load: true

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..5}; do
            if mysql -h127.0.0.1 -uroot -pexample -e "USE demo;" ; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Initialize database schema and user
        run: |
          mysql -h127.0.0.1 -uroot -pexample demo < backend/init.sql

      - name: Test backend container
        run: |
          docker run --rm --network host -e PORT=5000 -e DB_HOST=localhost -e DB_USER=testuser -e DB_PASSWORD=testpass -e DB_NAME=demo backend:test &
          sleep 4
          curl -f http://localhost:5000/api/users

      - name: Test frontend container
        run: |
          docker run --rm --network host -e PORT=3000 -e BACKEND_URL=http://localhost:5000 frontend:test &
          sleep 4
          curl -f http://localhost:3000/

# This workflow ensures Docker images build and basic endpoints respond
# You can extend it to push images or deploy to Kubernetes
